/*
 * This source file was generated by the Gradle 'init' task
 */
package test.practice;

import java.util.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Java Datastrucres"); 
        //1. Array List
        System.out.println("1. Dynamic Array");
        List<String> list = new ArrayList<>();
        list.add("Apple");
        list.add("Bananna");
        list.add("Cherry");
        System.out.println(" " + list);
        System.out.println(" Get index 1: " + list.get(1) + "\n");
        
        //2 LinkedList
        System.out.println("2. LinkedList Doubly linked list");
        LinkedList<Integer> linked = new LinkedList<>();
        linked.addFirst(10);
        linked.addLast(20);
        System.out.println("  "+ linked + "\n");

        //3 hashmap
        System.out.println("3. hashmap key-value");
        Map<String, Integer> ages = new HashMap<>();
        ages.put("Alice", 25);
        ages.put("Bob", 30);
        ages.put("charlie", 35);
        System.out.println("  "+ ages + "\n");

        //4 hashSet
        System.out.println("4. Hashset unique elements");
        Set<Integer> set = new HashSet<>();
        set.add(44);
        set.add(44);
        set.add(100);
        System.out.println("  "+ set + "\n");

        //5. TreeMap
        System.out.println("5. Tree map- (Sorted by key)");
        TreeMap<Integer, String> treeMap = new TreeMap<>();
        treeMap.put(100, "hundred");
        treeMap.put(1000, "Thousand");
        System.out.println("  "+treeMap +"\n");

        //6. PriorityQueue
        System.out.println("6. PrirityQueue - Min Heap");
        PriorityQueue<Integer> minHeap = new PriorityQueue<>();
        minHeap.offer(30);
        minHeap.offer(10);
        minHeap.offer(50);
        System.out.println("  "+minHeap+"\n");

        //7. 
        System.out.println("7. PrirityQueue - Max Heap");
        PriorityQueue<Integer> maxHeap = new PriorityQueue<>((a, b) -> b - a);
        maxHeap.offer(10);
        maxHeap.offer(50);
        maxHeap.offer(30);
        System.out.println("  "+maxHeap+"\n");

        //8. Stack 
        System.out.println("8. using ArrayDeque");
        Deque<String> stack = new ArrayDeque<>();
        stack.push("First");
        stack.push("Second");
        stack.push("Third");
        System.out.println(" Pop: "+ stack.pop());
        System.out.println(" Remaining: "+ stack + "\n");

        //9. Queue FIFO
        System.out.println("9. Queue FIFO");
        Queue<String> queue = new ArrayDeque<>();
        queue.offer("ONE");
        queue.offer("two");
        queue.offer("three");
        System.out.println(" Poll: " + queue.poll());
        System.out.println(" Remaining: "+ queue + "\n");

        //10. TreeSet
        System.out.println("10. TreeSet (Sorted + unique");
        TreeSet<Integer> treeSet = new TreeSet<>();
        treeSet.add(5);
        treeSet.add(1);
        treeSet.add(10);
        System.out.println("  "+ treeSet);
        System.out.println("All Data structres created");





    }
}
